import type { EventMeta } from '@/types'

const EVENT_MAP: Record<string, EventMeta> = {
  goal: {
    icon: '⚽',
    label: 'Goal',
    isHighlight: true,
    bgClass: 'bg-green-50',
    textClass: 'text-green-800',
    borderClass: 'border-green-300',
    dotClass: 'bg-green-500',
  },
  yellow_card: {
    icon: '🟨',
    label: 'Yellow Card',
    isHighlight: false,
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-800',
    borderClass: 'border-amber-300',
    dotClass: 'bg-amber-400',
  },
  red_card: {
    icon: '🟥',
    label: 'Red Card',
    isHighlight: true,
    bgClass: 'bg-red-50',
    textClass: 'text-red-800',
    borderClass: 'border-red-300',
    dotClass: 'bg-red-500',
  },
  substitution: {
    icon: '🔄',
    label: 'Substitution',
    isHighlight: false,
    bgClass: 'bg-blue-50',
    textClass: 'text-blue-800',
    borderClass: 'border-blue-200',
    dotClass: 'bg-blue-400',
  },
  penalty: {
    icon: '🥅',
    label: 'Penalty',
    isHighlight: true,
    bgClass: 'bg-orange-50',
    textClass: 'text-orange-800',
    borderClass: 'border-orange-300',
    dotClass: 'bg-orange-500',
  },
  offside: {
    icon: '🚩',
    label: 'Offside',
    isHighlight: false,
    bgClass: 'bg-gray-50',
    textClass: 'text-gray-700',
    borderClass: 'border-gray-200',
    dotClass: 'bg-gray-400',
  },
  foul: {
    icon: '⚠️',
    label: 'Foul',
    isHighlight: false,
    bgClass: 'bg-amber-50',
    textClass: 'text-amber-800',
    borderClass: 'border-amber-200',
    dotClass: 'bg-amber-400',
  },
  var: {
    icon: '📺',
    label: 'VAR Review',
    isHighlight: false,
    bgClass: 'bg-purple-50',
    textClass: 'text-purple-800',
    borderClass: 'border-purple-200',
    dotClass: 'bg-purple-400',
  },
  injury: {
    icon: '🏥',
    label: 'Injury',
    isHighlight: false,
    bgClass: 'bg-red-50',
    textClass: 'text-red-700',
    borderClass: 'border-red-200',
    dotClass: 'bg-red-400',
  },
  kickoff: {
    icon: '🏁',
    label: 'Kick Off',
    isHighlight: false,
    bgClass: 'bg-gray-50',
    textClass: 'text-gray-700',
    borderClass: 'border-gray-200',
    dotClass: 'bg-gray-400',
  },
  halftime: {
    icon: '⏸️',
    label: 'Half Time',
    isHighlight: false,
    bgClass: 'bg-slate-100',
    textClass: 'text-slate-700',
    borderClass: 'border-slate-300',
    dotClass: 'bg-slate-400',
  },
  fulltime: {
    icon: '🏆',
    label: 'Full Time',
    isHighlight: true,
    bgClass: 'bg-slate-100',
    textClass: 'text-slate-800',
    borderClass: 'border-slate-300',
    dotClass: 'bg-slate-500',
  },
  wicket: {
    icon: '🎯',
    label: 'Wicket',
    isHighlight: true,
    bgClass: 'bg-red-50',
    textClass: 'text-red-800',
    borderClass: 'border-red-300',
    dotClass: 'bg-red-500',
  },
  boundary: {
    icon: '4️⃣',
    label: 'Boundary',
    isHighlight: true,
    bgClass: 'bg-green-50',
    textClass: 'text-green-800',
    borderClass: 'border-green-300',
    dotClass: 'bg-green-500',
  },
  six: {
    icon: '6️⃣',
    label: 'Six',
    isHighlight: true,
    bgClass: 'bg-emerald-50',
    textClass: 'text-emerald-800',
    borderClass: 'border-emerald-300',
    dotClass: 'bg-emerald-500',
  },
  ace: {
    icon: '🎾',
    label: 'Ace',
    isHighlight: true,
    bgClass: 'bg-green-50',
    textClass: 'text-green-800',
    borderClass: 'border-green-300',
    dotClass: 'bg-green-500',
  },
  double_fault: {
    icon: '❌',
    label: 'Double Fault',
    isHighlight: false,
    bgClass: 'bg-red-50',
    textClass: 'text-red-700',
    borderClass: 'border-red-200',
    dotClass: 'bg-red-400',
  },
  break_point: {
    icon: '💥',
    label: 'Break Point',
    isHighlight: true,
    bgClass: 'bg-orange-50',
    textClass: 'text-orange-800',
    borderClass: 'border-orange-300',
    dotClass: 'bg-orange-500',
  },
}

const DEFAULT_META: EventMeta = {
  icon: '📢',
  label: 'Update',
  isHighlight: false,
  bgClass: 'bg-gray-50',
  textClass: 'text-gray-700',
  borderClass: 'border-gray-200',
  dotClass: 'bg-gray-400',
}

export function getEventMeta(eventType: string): EventMeta {
  return EVENT_MAP[eventType?.toLowerCase()] ?? DEFAULT_META
}

export const ALL_EVENT_TYPES = Object.keys(EVENT_MAP)
